FROM dunglas/frankenphp:1.1-builder-php8.2.16

ENV SERVER_NAME="http://"

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
    unzip \
    librabbitmq-dev \
    libpq-dev \
    supervisor

RUN install-php-extensions \
    gd \
    pcntl \
    opcache \
    pdo \
    pdo_mysql \
    redis

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

COPY ./.docker/php/php.ini /usr/local/etc/php/
COPY ./.docker/etc/supervisor.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN composer install

# Buat user surya dengan UID 1000
RUN groupadd -g 1000 surya && useradd -u 1000 -g surya -m surya

# Set permissions untuk Laravel dan folder project
RUN chown -R surya:surya /var/www/html \
    && chown -R surya:surya storage bootstrap/cache

EXPOSE 80 443

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
RUN chown -R 1000:1000 /var/www/html